---
title: "Output Summary"
subtitle: "`r paste0('Model Scenario: ', params$scenario)`" 
date: "`r paste0('Date Rendered: ', Sys.Date())`"
output: 
  html_document:
    toc: true
    toc_float: true
params:
  scenario:
    label: "Scenario"
    value: "base"
    input: text
  thin_percent:
    label: "Proportion of Posterior Samples to Retain?"
    value: 1
    input: numeric
  include_sim_years:
    label: "Include Simulated Years on Plots?"
    value: FALSE
  include_mcmc_diags:
    label: "Include MCMC Diagnostic Output?"
    value: TRUE
  include_fit_to_data:
    label: "Include Model Fit Output?"
    value: TRUE
  include_egg_to_parr_surv:
    label: "Include Egg-to-Parr Survival Output?"
    value: TRUE
  include_mean_length:
    label: "Include Mean Length Output?"
    value: TRUE
  include_surv_vs_length:
    label: "Length-based Survival Output?"
    value: TRUE
  include_capacity_vs_habitat:
    label: "Include Capacity vs. Habitat Output?"
    value: TRUE
  include_misc_process_model:
    label: "Include Misc. Process Model Output?"
    value: TRUE
  include_equiv_rates:
    label: "Include Equivilency Rate Output?"
    value: TRUE
  include_rho_params:
    label: "Include Process Model Correlation Output?"
    value: TRUE
  include_noise_term_diags:
    label: "Include Noise Term Diagnostic Output?"
    value: TRUE
  include_param_summaries:
    label: "Include Posterior Boxplot Output?"
    value: TRUE
  include_post_v_prior:
    label: "Include Posterior vs. Prior Densities?"
    value: TRUE
  include_jags_info:
    label: "Include JAGS Code/Data?"
    value: TRUE
editor_options: 
  chunk_output_type: console
---

```{r directories, include = F}
# set root directory to the project directory: one level up from this location
knitr::opts_knit$set(root.dir = "C:/Users/bstaton/Desktop/Staton/1_critfc/analyses/GR-sslcm/03-post-process")
```

```{r setup, include = FALSE}
# set global knitting options
knitr::opts_chunk$set(echo = FALSE, fig.align = "center", dpi = 600, out.width = "75%")

# load packages
source("../00-packages.R")

# load all necessary functions
invisible(sapply(list.files(path = "../01-functions", pattern = "\\.R$", full.names = T), source))

# set the input directory
in_dir = "../02-model/model-output"

# read information from this model
model_info = readRDS(file.path(in_dir, paste0("output_", params$scenario, ".rds")))

# extract the posterior samples
# post-MCMC thinning allowed to reduce run time of this document
if (params$thin_percent < 1) {
  post = post_thin(model_info$post, keep_percent = params$thin_percent)
} else {
  post = model_info$post
}

# extract the model data 
jags_data = model_info$jags_data
```

```{r dimension-ids}
# the years included by the model
all_yrs = as.numeric(dimnames(jags_data$phi_SL)[[1]])

# which years are "observable" for at least some quantities?
observable = 2:jags_data$ny_obs

# which years are simulated for at least some quantities?
simulated = which(!(all_yrs %in% all_yrs[observable]) & all_yrs > min(all_yrs[observable]))

# which years should be included in time series plots?
if (params$include_sim_years) {
  ts_yrs = c(observable, simulated)
} else {
  ts_yrs = observable
}

# which years can be plotted for SARs? Drop off last kmax years
# since brood year adult returns not complete
sar_yrs = ts_yrs[-((length(ts_yrs) - jags_data$kmax + 1):length(ts_yrs))]

# population names
pops = colnames(jags_data$Ra_obs)

# origin names
origins = c("NOR", "HOR")

# dimension IDs
i_fall   = 1  # fall migrants are i = 1
i_spring = 2  # spring migrants are i = 2,
o_nor    = 1  # natural origin are o = 1,
o_hor    = 2  # hatchery origin are o = 2,
j_cat    = 1  # Catherine Creek is j = 1
j_los    = 2  # Lostine River is j = 2
j_min    = 3  # Minam River is j = 3
j_ugr    = 4  # Upper Grande Ronde River is j = 4
k_3      = 1  # age 3 is k = 1
k_4      = 2  # age 4 is k = 2
k_5      = 3  # age 5 is k = 3

# ko represents "age/origin" combo
# e.g., ko = 1 is age 3 NORs
# e.g., ko = 5 is age 4 HORs
# these objects specify which elements of ko are for different aggregations of these
ko_age = list(
  ko_3 = c(1, 4),
  ko_4 = c(2, 5),
  ko_5 = c(3, 6)
)

ko_origin = list(
  ko_nor = 1:3,
  ko_hor = 4:6
)

# make the labels for which elements of the rho matrices contain unique elements
dummy_cols = matrix(rep(1:jags_data$nj, each = jags_data$nj), jags_data$nj, jags_data$nj)
dummy_rows = matrix(rep(1:jags_data$nj, jags_data$nj), jags_data$nj, jags_data$nj)
vcov_cols = dummy_cols[lower.tri(dummy_cols)]
vcov_rows = dummy_rows[lower.tri(dummy_rows)]
vcov_inds = paste0("[", vcov_rows, ",", vcov_cols, "]")
vcov_labels = paste0(pops[vcov_rows], "-", pops[vcov_cols])
```

```{r set-plot-opts}
# select main colors
main_cols = c(
  "model" = "salmon",
  "model2" = "royalblue",
  "data" = "royalblue"
)

# set the transparent versions based on main color
tran_cols = sapply(main_cols, scales::alpha, alpha = 0.25)

# size of points on figures
pt_cex = 1.4

# figure dimensions: a figure of two panels (inches)
p2_width = 6.5
p2_height = 2.75

# figure dimensions: a figure of three panels (inches)
p3_width = 6.5
p3_height = 2

# figure dimensions: a figure of four panels (inches)
p4_width = 6.5
p4_height = 4.5

# figure dimensions: a figure of 6 panels (inches)
p6_width = 6.5
p6_height = 3.75

# actual ylim to use for [0,1]
# allows showing panel label in upper corner
ylim_01 = c(0, 1.05)
```

```{r model-info, child = "output-plots-children/01-model-info.Rmd"}
```

```{r mcmc, child = "output-plots-children/02-mcmc-diags.Rmd", eval = params$include_mcmc_diags}
```

```{r fit-to-data, child = "output-plots-children/03-fit-to-data.Rmd", eval = params$include_fit_to_data}
```

```{r egg-to-parr-surv, child = "output-plots-children/04-egg-to-parr-surv.Rmd", eval = params$include_egg_to_parr_surv}
```

```{r mean-length, child = "output-plots-children/05-length.Rmd", eval = params$include_mean_length}
```

```{r length-based-values, child = "output-plots-children/06-length-based-survival.Rmd", eval = params$include_surv_vs_length}
```

```{r capacity-vs-habitat, child = "output-plots-children/07-capacity-vs-habitat.Rmd", eval = params$include_capacity_vs_habitat}
```

```{r misc-process-model, child = "output-plots-children/08-misc-process-model.Rmd", eval = params$include_misc_process_model}
```

```{r equiv-rates, child = "output-plots-children/09-equiv-rates.Rmd", eval = params$include_equiv_rates}
```

```{r rho-params, child = "output-plots-children/10-rho-params.Rmd", eval = params$include_rho_params}
```

```{r noise-term-diags, child = "output-plots-children/11-noise-term-diags.Rmd", eval = params$include_noise_term_diags}
```

```{r param-summaries, child = "output-plots-children/12-param-summaries.Rmd", eval = params$include_param_summaries}
```

```{r post-v-prior, child = "output-plots-children/13-post-vs-prior.Rmd", eval = params$include_post_v_prior}
```

```{r jags-info, child = "output-plots-children/14-jags-model-info.Rmd", eval = params$include_jags_info}
```
