---
editor_options: 
  chunk_output_type: console
---

# Model Info {.tabset .tabset-pills}

**Scenario Name:** `r params$scenario`

**Post-MCMC Percent of Samples Retained:** `r paste0(params$thin_percent * 100, "%")`

## Attributes

```{r mcmc-dims}
# query the dimensions of the posterior samples
dims = post_dim(post)

# build a data frame for printing
df = data.frame(Quantity = c("Burn-in + Adapt Iters", "Post Burn-in Iters", "Thinning Interval", "Chains", "Saved Iters", "Monitored Quantities"), Value = unname(dims))

# render the table
kable(df, format.args = list(big.mark = ","), caption = "Dimensions of the MCMC run. If post-MCMC percent of samples retained (above) is less than 100%, the numbers in this table are unreliable.") %>%
  kable_styling(full_width = F, bootstrap_options = c("striped", "condensed")) %>%
  column_spec(1, bold = TRUE)
```

## Run Time

```{r mcmc-time-info}
# Calculate hours per 10,000 iterations
hrs_per_ten_thousand_iters = with(model_info$jags_dims, {
  # calculation of total iters differs if parallel or not
  if (parallel) {
    total_iters = n_adapt + n_post + n_burn
  } else {
    total_iters = (n_adapt + n_post + n_burn) * n_chains
  }
  ten_thousands_of_total_iters = total_iters/10000
  
  # calculate hours elapsed
  time_diff = as.POSIXct.default(model_info$jags_time["stoptime"]) - as.POSIXct.default(model_info$jags_time["starttime"])
  time_number = as.numeric(time_diff)
  time_units = attributes(time_diff)$units
  hour_convert = switch(time_units,
                        "secs" = 3600,
                        "mins" = 60,
                        "hours" = 1,
                        "days" = 1/24)
  hours_diff = time_number/hour_convert
  
  # calculate/round rate
  round(hours_diff/ten_thousands_of_total_iters, 2)
})

# combine relevant info into a data frame
df = data.frame(Value = c(model_info$jags_time, ifelse(model_info$jags_dims$parallel, "Yes", "No"), hrs_per_ten_thousand_iters))
rownames(df) = c("Time Started", "Time Ended", "Time Elapsed", "Chains Ran in Parallel?", "Hours Per 10,000 Iterations")

# make a kable for printing in output
kable(df, caption = "Run time for MCMC sampling. Includes any time the computer spent sleeping and not running MCMC. If post-MCMC percent of samples retained (above) is less than 100%, the numbers in this table are unreliable.") %>%
  kable_styling(full_width = F, bootstrap_options = "condensed") %>%
  column_spec(1, bold = TRUE)
```
