---
editor_options: 
  chunk_output_type: console
---

# Parr Capacity vs. Habitat Relationship {.tabset .tabset-pills}

## Scatterplot

Error bars represent the central 80% of the posterior. The many grey lines are individual posterior draws.

```{r beta-v-habitat-relationship, fig.width = 5, fig.height = 5}
# extract posterior summaries of the capacity parameters
beta_ests = post_summ(post, "^beta[", probs = c(0.1, 0.5, 0.9))

# extract posterior samples of the slope parameter
beta_per = post_subset(post, "lambda", TRUE)

# create a sequence of WUL values to predict capacity at
wul_seq = seq(0, max(jags_data$wul) * 1.1, length = 30)

# obtain the regression line for each posterior sample
pred_beta = t(sapply(beta_per, function(slope) wul_seq * slope))

# select a subset of posterior samples at random to draw
i = sample(1:post_dim(post, "saved"), min(100, post_dim(post, "saved")), replace = FALSE)

# empty plot with correct labeling/dimensions
par(mar = c(3,3,1,1), mgp = c(2,0.35,0), tcl = -0.15)
plot(1,1, type = "n", xlim = range(wul_seq),
     ylim = c(0, max(beta_ests["90%",], beta_ests["90%",], pred_beta[i,])),
     xlab = "Weighted Usable Length (km)",
     ylab = "Parr Capacity (000s)", yaxt = "n")
at_y = axisTicks(par("usr")[3:4], log = FALSE)
axis(side = 2, at = at_y, labels = at_y/1000)

# draw the random regression lines
junk = sapply(i, function(k) lines(pred_beta[k,] ~ wul_seq, col = alpha("grey25", 0.15)))

# draw the posterior mean regression line
lines(apply(pred_beta, 2, mean) ~ wul_seq, lwd = 3, lty = 2)

# draw the population-specific capacity estimates w/error bars and labels
points(beta_ests["mean",] ~ jags_data$wul, cex = 1.5, pch = 16)
segments(jags_data$wul, beta_ests["10%",], jags_data$wul, beta_ests["90%",])
text(x = jags_data$wul, y = beta_ests["mean",], labels = c("CAT", "LOS", "MIN", "UGR"), pos = c(2,4,4,4), font = 2)
```

## Slope Parameter

```{r beta-v-habitat-slope}
# extract posterior summary of slope
est = post_summ(post, "^lambda$")
colnames(est) = "slope"

# print a table 
kable(t(est), digits = 0, format.args = list(big.mark = ",")) %>%
  kable_styling(full_width = FALSE, bootstrap_options = c("condensed", "striped"))
```
